config/routes.rb
Rails.application.routes.draw do

  resources 'books'

  get 'scrape', to:'scrape#index', as: 'scrape'
  post 'rescrape', to: 'scrape#rescrape', as: 'rescrape'

  get 'admin', to: 'scrape#index', as: 'admin'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  def self.search(search)
    where("isbn13 LIKE ? OR title LIKE ? OR author_name LIKE ? or skill LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
	if params[:search]
    @books = Book.search(params[:search]).order("created_at DESC")
  else
    @books = Book.all.order("created_at DESC")
  end
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/scrape_controller.rb
class ScrapeController < ApplicationController

  def index
    # asd
  end

  def rescrape
    # send this to a background job
    password = params['password']
    puts "entered password: #{password}"
    if password == Rails.application.secrets.admin_password
      ScrapeJob.perform_later
      redirect_to root_path
    else
      redirect_to admin_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scrape_helper.rb
module ScrapeHelper

  # Result class to help consolidate results
  class Result

    def initialize
      @title = -1
      @isbn = -1
      @shop = -1
      @url = -1
      @price = -1
      @authorName = -1
      @pictureUrl = -1
      @desc = -1
    end

    def setTitle(title)
      @title = title
    end
    def getTitle
      return @title
    end

    def setIsbn(isbn)
      @isbn = isbn
    end
    def getIsbn
      return @isbn
    end

    def setShop(shop)
      @shop = shop
    end
    def getShop
      return @shop
    end

    def setUrl(url)
      @url = url
    end
    def getUrl
      return @url
    end

    def setPrice(price)
      @price = price
    end
    def getPrice
      return @price
    end

    def setAuthorName(authorName)
      @authorName = authorName
    end
    def getAuthorName
      return @authorName
    end

    def setPictureUrl(pictureUrl)
      @pictureUrl = pictureUrl
    end
    def getPictureUrl
      return @pictureUrl
    end

    def setDesc(desc)
      @desc = desc
    end
    def getDesc
      return @desc
    end

  end
  # End Results class

end

app/views/books/_delete_modal.html.erb
<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="settingsModalLabel">Settings</h4>
      </div>
      <div class="modal-body">
        <form id="delete" role="form">
          <label for="delete-book-id">Delete this entry?</label>
          <input type="hidden" class="form-control delete-book-id" name="delete-book-id" required>
          <button type="submit" class="btn btn-danger">Confirm Delete</button>
        </form>
        <div id="delete-spinner" style="display:none">
          <p>Deleting entry... Please wait...</p>
          <div class="load-bar">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button id=close-delete-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/books/_edit_modal.html.erb
<!-- Edit Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="settingsModalLabel">Edit</h4>
      </div>
      <div class="modal-body">
        <form id="edit" role="form">
          <div class="form-group">
            <input class="form-control book-id" type="hidden" name="id">
            <label for="title">Title:</label>
            <input class="form-control book-title" name="title" placeholder="Book Title" required>
            <label for="author">Author:</label>
            <input class="form-control book-author" name="author" placeholder="Author" required>
            <label for="author-bio">Author Bio:</label>
            <input class="form-control book-author-bio" name="author-bio" placeholder="Author Bio" required>
            <label for="description">Description:</label>
            <input class="form-control book-description" name="description" placeholder="Book Description" required>
            <label for="price">Price in USD:</label>
            <input class="form-control book-price" type="number" step="0.01" name="price" placeholder="Book Price" required>
            <label for="rating">Rating:</label>
            <input class="form-control book-rating" name="rating" placeholder="Book Rating" required>
            <label for="image-url">Cover Image Url:</label>
            <input class="form-control book-image-url" name="image-url" placeholder="Cover Image Url" required>
            <label for="book-url">Amazon Page Url:</label>
            <input class="form-control book-url" name="book-url" placeholder="Amazon Page Url" required>
          </div>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
        <div id="edit-spinner" style="display:none">
          <p>Making changes... Please wait...</p>
          <div class="load-bar">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button id=close-edit-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for :skill do |f| %>
  <%= f.association :mc_wing, label: 'Choose the skill:', label_method: :wingname, value_method: :wingid, include_blank: false %>
  <%= f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full'} } %>
  <br>
  <%= f.button :submit, 'Submit', class: 'radius success' %>
  <%= link_to "Cancel", :back, class: 'radius button alert' %>
<% end %>

<%= simple_form_for :book, url: mc_locker_locker_allocations_path, method: :get, remote: true do |f|  %>
  <%= f.input :year, collection: LockerRound.select('acad_year').distinct.order('acad_year desc'), label_method: :acad_year, value_method: :acad_year, include_blank: false %>
  <%= f.button :submit, 'Retrieve Allocations', class: 'radius info button expand', name: 'retrieve' %>
<% end %>


<form id="filter" role="form">
  <div class="form-group">
    <label for="skill-filter">Choose the skill:</label>
    <select name="skill-filter" id="skill-filter" class="form-control">
    </select>
  </div>
  <button type="submit" class="btn btn-success">See Books</button>
</form>

app/views/books/_results.html.erb
<div id="results" class="col-xs-12">
  
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="http://www.comp.nus.edu.sg/~lweikit/materialize/css/materialize.css">

  <!-- Compiled and minified JavaScript -->
  <script src="http://www.comp.nus.edu.sg/~lweikit/materialize/js/materialize.js"></script>


  <% if @books.any? %>
    <div style="text-align: center;">
      <p>
        <strong><%= @books.count %> books!</strong>
      </p>
    </div>

    <% @books.each do |book| %>
      <div class="col m4 s6">
        <div class="card sticky-action large hoverable" id='<%= "book-#{book.id}" %>'>
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src='<%= book.image_url %>'>
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4 truncate"><%= book.title %></span>
            $<%= format '%.2f', book.price %>
            <div class="card-action">
              FOUND @ <%= link_to book.shop, book.url %>
              <div class="chip right"><%= book.skill %></div>
            </div>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">By <%= link_to book.author_name, 'http://google.com/search?q='+book.author_name %><i class="material-icons right">close</i></span>
            $<%= format '%.2f', book.price %>
            <div class="right-align"><%= book.isbn13 %></div>
            <p class="left-align"><%= book.title %></p>
          </div>
        </div>
      </div>
      <!-- <tr id='<%= "book-#{book.id}" %>'>
        <td><%= book.isbn13 %></td>
        <td><%= link_to book.title, book.url, target: '_blank' %></td>
        <td><%= book.author_name %></td>
        <td><%= format '%.2f', book.price %></td>
        <td><%= image_tag book.image_url %></td>
        <td><%= book.skill %></td>
        <td><%= book.shop %></td>
      </tr> -->
    <% end %>

    <!-- <table width="100%" class="table-striped">
      <thead>
      <tr>
        <th>ISBN-13</th>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Image</th>
        <th>Topic</th>
        <th>Store</th>
      </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr id='<%= "book-#{book.id}" %>'>
          <td><%= book.isbn13 %></td>
          <td><%= link_to book.title, book.url, target: '_blank' %></td>
          <td><%= book.author_name %></td>
          <td><%= format '%.2f', book.price %></td>
          <td><%= image_tag book.image_url %></td>
          <td><%= book.skill %></td>
          <td><%= book.shop %></td>
        </tr>
      <% end %>
      </tbody>
    </table> -->
  <% else %>
    <div style="text-align: center;">
      <p>
        <strong>No books!</strong>
      </p>
    </div>
  <% end %>

</div>

app/views/books/_settings_modal.html.erb
<!-- Settings Modal -->
<div class="modal fade" id="settingsModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="settingsModalLabel">Settings</h4>
      </div>
      <div class="modal-body">
        <form id="rescrape" role="form">
          <label for="rescrape-yn">Rescrape Backend Data (Warning: This takes a long time and the website will be slow until it finishes scraping)</label>
          <select id="rescrape-yn" name="rescrape-yn">
            <option value="no">No</option>
            <option value="yes">Yes</option>
          </select>
          <button type="submit" class="btn btn-danger">Rescrape</button>
        </form>
        <div id="spinner" style="display:none">
          <p>Rescraping data... Please wait...</p>
          <p>This will take some time. Why not visit <a href="http://nuscomputing.com/" target="_blank">NUS Students' Computing Club</a> in the meantime?</p>
          <div class="load-bar">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
          </div>
        </div>
        <div id="rescrape-success" style="display:none;">
          <p>Rescrape Success!</p>
          <div class="btn btn-success" onclick="window.location.reload()">Refresh</div>
        </div>
      </div>
      <div class="modal-footer">
        <button id=close-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<table>
	<tr>
		<td width='50%'><p><%= link_to 'Home', root_path %></p></td>
		<td width='50%'><p><%= link_to 'Admin Console', admin_path, :class=>"color"%></p></td>
	</tr>
	<tr>
		<td colspan=2><h1>BOOKS</h1></td>
	</tr>
	<tr>
		<td colspan=2 align=center>
			<%= form_tag(books_path, id: "search-form", method: "get") do%>
			<%= text_field_tag :search, params[:search], placeholder: "Search... (ISBN, Author, Language)", :class => 'text'%>
			<% end %>
		</td>
	</tr>
</table>
<div class="row">
  <%= render 'results' %>	
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/home/index.html.erb
<div class="centered">

<table>
	<tr>
		<td colspan=2><h1>iamascrapbook</h1></td>
	</tr>
	<tr>
		<td colspan=2><h2>Intelligent Amazon Book Scraper</h2></td>
	</tr>
	<tr>
		<td colspan=2 align=center>
			<%= form_tag(books_path, id: "search-form", method: "get") do%>
			<%= text_field_tag :search, params[:search], placeholder: "Search... (ISBN, Author, Language)", :class => 'text'%>
			<% end %>
		</td>
	</tr>
	<tr>
		<td><p><%= link_to 'See all our books!', books_path, :class=>"color"%></p></td>
		<td><p><%= link_to 'Admin Console', admin_path, :class=>"color"%></p></td>
	</tr>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>iamascrapbook | Intelligent Amazon Scraper for Books</title>

    <!-- JQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">

      <%= yield %>

    </div>

  </body>
</html>

app/views/scrape/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>admin</h1>
  </div>

	<center>
	  <%= form_tag(rescrape_path, method: 'post') do %>
	    <p>Rescrape data to update the database with new books and prices.<br>
	      Warning, the scraping will take a long time to finish!</p>
	    <%= label_tag('password', 'Admin password:') %>
	    <%= password_field_tag('password', '', autofocus: 'true') %>
	    <%= submit_tag('Rescrape', class: 'btn btn-danger') %>
	  <% end %>
	</center>

  <p><%= link_to 'Home', root_path %></p>
  <p><%= link_to 'See all our books!', books_path %></p>
</div>

app/views/scrape/scrape.html.erb
<h1>Scrape#scrape</h1>
<p>Find me in app/views/scrape/scrape.html.erb</p>

app/views/scrape/test.html.erb
This is a page
<br>
<%= @results.inspect %>